### ISSUE TITLE
Ewallet Balance PHPDoc

### ISSUE THREAD

**Issue by natepage** [loyaltycorp/eoneopay-phpsdk#54]
Hey there,

The PHPDoc on `EoneoPay\PhpSdk\Endpoints\Ewallet` defines a method to get the balances as `@method mixed[]|null getBalances()` which tells us it will either return an array or null.

But the PHPDoc on `EoneoPay\PhpSdk\Traits\EwalletTrait` for the `$balances` property is `@var \EoneoPay\PhpSdk\Endpoints\Balance|null` which tells us it will either return a Balance object or null.

Because of that the auto-completion in PHPStorm told us we're dealing with an array so it broke when we started to test it.

**Comment by brendonofficial** [comment]
@natepage The typehint has been updated and available in tag `1.0.0-RC6`.
